# Usage: python merge_tables.py file1.tsv file2.tsv ... filen.tsv 
# Purpose: merge tables generated by make_tables.py and make heatmap figure 

import pandas as pd
import argparse
import matplotlib.pyplot as plt
from matplotlib import colors
import numpy as np
import re
import sys
from functools import reduce

args = sys.argv
files = []
for arg in args[1:len(args)]:
	files.append(arg)

dataframe_list = []
for i in range(len(files)): 
	temp_df = pd.read_table(files[i])
	temp_df.columns = ['GOSlimTerm',files[i]]
	dataframe_list.append(temp_df)

names = []
for fname in files:
    res = re.findall("(.*).blast", fname)
    if not res: continue
    names.append(res[0])

Output_df = reduce(lambda x, y: pd.merge(x, y, on = 'GOSlimTerm', how = 'outer'),dataframe_list)
Output_df = Output_df.fillna(0)
Output_df.to_csv("GOSlim_aggregated.tsv", sep='\t')

table_merge_num = Output_df.iloc[0:,1:]
GOSlim_list = list(Output_df["GOSlimTerm"])

fig, ax = plt.subplots(figsize=(15,15))
im = ax.imshow(table_merge_num, cmap="rainbow")
ax.set_title("Heatmap of GOSlim Categories", size=20)
ax.set_xticks(np.arange(len(names))) 
ax.set_xlabel('Sample')
ax.set_xticklabels(names)
plt.setp(ax.get_xticklabels(),rotation=45, ha="right", rotation_mode="anchor")

ax.set_ylabel('GO Slim Category') 
ax.set_yticks(np.arange(len(GOSlim_list)))
ax.set_yticklabels(GOSlim_list)

fig.tight_layout()
cbar = ax.figure.colorbar(im, ax=ax, shrink=0.5)
ax.set_facecolor("white")

plt.savefig("GOSlim_heatmap.png", format='png',dpi=300)

fig, ax = plt.subplots(figsize=(15,15))
im = ax.imshow(table_merge_num, cmap="rainbow", norm=colors.SymLogNorm(vmin=0, vmax=table_merge_num.to_numpy().max(), linthresh=0.001, base=10))
ax.set_title("Heatmap of GOSlim Categories", size=20)
ax.set_xticks(np.arange(len(names)))
ax.set_xlabel('Sample')
ax.set_xticklabels(names)
plt.setp(ax.get_xticklabels(),rotation=45, ha="right", rotation_mode="anchor")

ax.set_ylabel('GO Slim Category')
ax.set_yticks(np.arange(len(GOSlim_list)))
ax.set_yticklabels(GOSlim_list)

fig.tight_layout()
cbar = ax.figure.colorbar(im, ax=ax, shrink=0.5)
ax.set_facecolor("white")

plt.savefig("GOSlim_heatmap_lognorm.png", format='png',dpi=300)
